#!/usr/bin/env bash
# Build llms-full.txt by concatenating all reference content.
# This file is consumed by LLMs as a single-file knowledge dump.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="${REPO_ROOT}/llms-full.txt"

{
    # Start with llms.txt
    cat "${REPO_ROOT}/llms.txt"

    echo ""
    echo "================================================================"
    echo "= FULL REFERENCE (auto-generated by build-llms-full.sh)"
    echo "================================================================"
    echo ""

    # Package references
    for ref in "${REPO_ROOT}"/packages/*/reference.md; do
        if [ -f "$ref" ]; then
            pkg_dir="$(basename "$(dirname "$ref")")"
            echo ""
            echo "----------------------------------------------------------------"
            echo "-- ${pkg_dir} reference"
            echo "----------------------------------------------------------------"
            echo ""
            cat "$ref"
            echo ""
        fi
    done

    # Cookbooks (Python files only)
    for cookbook in "${REPO_ROOT}"/cookbooks/*.py; do
        if [ -f "$cookbook" ]; then
            name="$(basename "$cookbook")"
            echo ""
            echo "----------------------------------------------------------------"
            echo "-- cookbook: ${name}"
            echo "----------------------------------------------------------------"
            echo ""
            cat "$cookbook"
            echo ""
        fi
    done

    # Guides
    for guide in quant-pitfalls.md data-providers.md; do
        guide_path="${REPO_ROOT}/guides/${guide}"
        if [ -f "$guide_path" ]; then
            echo ""
            echo "----------------------------------------------------------------"
            echo "-- guide: ${guide}"
            echo "----------------------------------------------------------------"
            echo ""
            cat "$guide_path"
            echo ""
        fi
    done

} > "$OUTPUT"

line_count=$(wc -l < "$OUTPUT")
approx_tokens=$(echo "$line_count * 1.3" | bc | cut -d. -f1)

echo "Built ${OUTPUT}"
echo "  Lines: ${line_count}"
echo "  Approx tokens: ${approx_tokens}"
